trigger:
- master

pool: Default

steps:
- script: hostname

#- task: GitHubComment@0
#  inputs:
#    gitHubConnection: 'github.com_shiraZadok'
#    repositoryName: 'shiraZadok/AzureRmPipeline_MTC'


#Task 2
#Create an ARM template for storage account
#And create 2 storage accounts
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      #New-AzResourceGroupDeployment `
      -Name 'Deployment-Create_the_first_storageaccount' `
      -ResourceGroupName 'ShiraStorageAccount-rg' `
      -TemplateFile 'ARM_Templete_StorageAccount.json' `
      -TemplateParameterFile 'parameters_sa1.json'

      New-AzResourceGroupDeployment `
      -Name 'Deployment-Create_the_second_storageaccount' `
      -ResourceGroupName 'ShiraStorageAccount-rg' `
      -TemplateFile 'ARM_Templete_StorageAccount.json' `
      -TemplateParameterFile 'parameters_sa2.json'


#Task 3
#Create an ARM template for a Windows server
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      
      #New-AzResourceGroupDeployment `
      #-Name Deployment_create_VM `
      #-ResourceGroupName ShiraStorageAccount-rg `
      #-TemplateFile 'WindowsServerTemplate.json' `
      #-TemplateParameterFile 'WindowsServerParameters.json'

#Task 5
#Create, Upload and Copy 100 blobs from Storage account A to B
#Execute it on the windows server
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $SubscriptionID= "a8108c2b-496c-424d-8347-ecc8afb6384c"
      Set-AzContext -Subscription $SubscriptionID
      Invoke-AzVMRunCommand `
       -ResourceGroupName 'ShiraStorageAccount-rg' `
       -Name ShiraWindowsServer `
       -CommandId 'RunPowerShellScript' `
       -ScriptPath Create_Uplad_CopyBlobs.ps1

#- task: AzureMonitorAlerts@0
#  inputs:
#    ResourceGroupName: 'ShiraStorageAccount-rg'
#    ResourceType: 'Microsoft.Storage/storageAccounts'
#    ResourceName: 

