trigger:
- master

pool: Default

steps:
- script: hostname

#- task: GitHubComment@0
#  inputs:
#    gitHubConnection: 'github.com_shiraZadok'
#    repositoryName: 'shiraZadok/AzureRmPipeline_MTC'

#Task 2
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
    
    #New-AzResourceGroupDeployment -Name Deployment-Create_the_first_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json' -TemplateParameterFile 'parameters_sa1.json'
     #New-AzResourceGroupDeployment -Name Deployment-Create_the_second_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json' -TemplateParameterFile 'parameters_sa2.json'
      #For ($i=0; $i -lt 1; $i++) {
     #New-AzResourceGroupDeployment -Name Deployment-Create_the_first_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'Generally_Template_StorageAccount.json'}

#Task 3
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      
      #New-AzResourceGroupDeployment -Name Deployment_create_VM -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'WindowsServerTemplate.json' -TemplateParameterFile 'WindowsServerParameters.json'

#Task 5
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $ctx = (Get-AzStorageAccount -ResourceGroupName "ShiraStorageAccount-rg" -Name "mysorage11").Context
      $containerName = "firstcontainer"
       #New-AzStorageContainer -Name $containerName -Context $ctx -Permission blob
      Set-AzStorageBlobContent -File "C:\Users\ShiraZadok\Microsoft\microsoft-1.png" `
      -Container $containerName `
      -Blob "microsoft-1.png" `
      -Context $ctx