trigger:
- master

pool: Default

steps:
- script: hostname

#- task: GitHubComment@0
#  inputs:
#    gitHubConnection: 'github.com_shiraZadok'
#    repositoryName: 'shiraZadok/AzureRmPipeline_MTC'

#Task 2
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
    
    #New-AzResourceGroupDeployment -Name Deployment-Create_the_first_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json' -TemplateParameterFile 'parameters_sa1.json'
     #New-AzResourceGroupDeployment -Name Deployment-Create_the_second_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json' -TemplateParameterFile 'parameters_sa2.json'
      #For ($i=0; $i -lt 1; $i++) {
     #New-AzResourceGroupDeployment -Name Deployment-Create_the_first_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'Generally_Template_StorageAccount.json'}

#Task 3
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      
      #New-AzResourceGroupDeployment -Name Deployment_create_VM -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'WindowsServerTemplate.json' -TemplateParameterFile 'WindowsServerParameters.json'

#Task 5
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $ResourceGroupName= "ShiraStorageAccount-rg"
      $srcStorageAccountName = "mysorage11"
      $destStorageAccountName = "mysorage22"

      $srcStorageAccount = (Get-AzStorageAccount -ResourceGroupName $ResourceGroupName -Name $srcStorageAccountName).Context
      $destStorageAccount = (Get-AzStorageAccount -ResourceGroupName $ResourceGroupName -Name $destStorageAccountName).Context
      $srcContainer = "sourcecontainer"
      $destContainer = "destcontainer"

       #Create source and destination container
      #New-AzStorageContainer -Name $srcContainer -Context $srcStorageAccount -Permission blob
      #New-AzStorageContainer -Name $destContainer -Context $destStorageAccount -Permission blob

      $srcStorageKey = Get-AzStorageAccountKey -Name $srcStorageAccountName `
                                         -ResourceGroupName $ResourceGroupName 
      $destStorageKey = Get-AzStorageAccountKey -Name $destStorageAccountName `
                                          -ResourceGroupName $ResourceGroupName

      $srcContext = New-AzStorageContext -StorageAccountName $srcStorageAccountName `
                                   -StorageAccountKey $srcStorageKey.Value[0]
      $destContext = New-AzStorageContext -StorageAccountName $destStorageAccountName `
                                    -StorageAccountKey $destStorageKey.Value[0]
      $blobName= "100Blobs.rar"

       #Uplad blobs to the conatainer
      Set-AzStorageBlobContent -File "C:\Users\ShiraZadok\Microsoft\100Blobs.rar" `
      -Container $srcContainer `
      -Blob $blobName `
      -Context $srcContext -Force
       #azcopy copy 'https://mysorage11.blob.core.windows.net/sourcecontainersp=r&st=2021-08-26T16:30:07Z&se=2021-08-27T00:30:07Z&spr=https&sv=2020-08-04&sr=b&sig=0AxUYlrfSH57HXFNxePlsbZB0hPmdl%2BVq%2B%2Flw9GE10g%3D' 'https://mysorage22.blob.core.windows.net/destcontainer' --recursive

       #Copy blobs from SrcContainer to DestContainer
       $copyOperation = Start-AzStorageBlobCopy -SrcBlob $blobName `
                                         -SrcContainer $srcContainer `
                                         -Context $srcContext `
                                         -DestBlob $blobName `
                                         -DestContainer $destContainer `
                                         -destContext $destContext
