stages:
  - stage: Build
    jobs:
    - job: Build

  - stage: Deploy
    jobs:
    - job: Deploy
      pool: Default
      steps:
          - script: hostname
          - task: CmdLine@2
            inputs:
              script: 'echo Write your commands here.' 