trigger:
- master

pool: Default


#Global Variables
variables:
 myResourceGroupName: ShiraStorageAccount-rg
 subscriptionName: "MSEC_Candidates_Homeworks"
 subscriptionID: "a8108c2b-496c-424d-8347-ecc8afb6384c"
 location: "eastus"

#Connect to the self-hosted agents
steps:
- script: hostname

      

#Task 6
#Create Monitor and Dashboard
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      
      #Create a dashboard for the Vm-shiraWindowsServer2
      #New-AzResourceGroupDeployment -Name Deployment_Create_Dashboard `
      #-ResourceGroupName $(myResourceGroupName) `
      #-TemplateFile 'DashboardTemplate.json' `
      #-TemplateParameterFile 'DashboardParametersFile.json'

      ###list the metric definition of the storage accounts
      #Storage Account A
      $resourceId_SA_A = "/subscriptions/a8108c2b-496c-424d-8347-ecc8afb6384c/resourceGroups/ShiraStorageAccount-rg/providers/Microsoft.Storage/storageAccounts/shirastorageaccount0a"
      Get-AzMetricDefinition -ResourceId $resourceId_SA_A
      Get-AzMetric -ResourceId $resourceId_SA_A -MetricNames "UsedCapacity" -TimeGrain 01:00:00
      #Storage Account B
      $resourceId_SA_B = "/subscriptions/a8108c2b-496c-424d-8347-ecc8afb6384c/resourceGroups/ShiraStorageAccount-rg/providers/Microsoft.Storage/storageAccounts/shirastorageaccount0b"
      Get-AzMetricDefinition -ResourceId $resourceId_SA_B
      Get-AzMetric -ResourceId $resourceId_SA_B -MetricNames "UsedCapacity" -TimeGrain 01:00:00

