trigger:
- master

pool: Default

steps:
- script: hostname

#- task: GitHubComment@0
#  inputs:
#    gitHubConnection: 'github.com_shiraZadok'
#    repositoryName: 'shiraZadok/AzureRmPipeline_MTC'

#Task 2
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
         For ($i=0; $i -lt 2; $i++) {
          # New-AzResourceGroupDeployment -Name DeploymentSA -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json'
          $StorageAccount = New-AzStorageAccount -StorageAccountName A -Type 'Standard_LRS' -ResourceGroupName ShiraStorageAccount-rg -Location "East US"
                 }

#Task 3
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
#     $c = Get-Credential -UserName 'shiraZadok'
#     New-AzVM -Name ShiraStorageAccount-rg -Credential $c