stages:
  - stage: Deploy
    jobs:
    - job: Deploy
      pool: Default
      steps:
          - script: hostname
          - task: CmdLine@2
            inputs:
              script: $containerName = "quickstartblobs"
                      New-AzStorageContainer -Name $containerName -Context $ctx -Permission blob. 