trigger:
- master

pool: Default

steps:
- script: hostname

- task: GitHubComment@0
  inputs:
    gitHubConnection: 'github.com_shiraZadok'
    repositoryName: 'shiraZadok/AzureRmPipeline_MTC'

#Task 2
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
          New-AzResourceGroupDeployment -Name Deployment-Create_the_first_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json' -TemplateParameterFile 'parameters_sa1.json'
          New-AzResourceGroupDeployment -Name Deployment-Create_the_second_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json' -TemplateParameterFile 'parameters_sa2.json'

#Task 3
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      New-AzResourceGroup -Name ShiraStorageAccount-rg -Location "East US"
      New-AzResourceGroupDeployment `
          -ResourceGroupName ShiraStorageAccount-rg `
          -TemplateUri "https://github.com/shiraZadok/AzureRmPipeline_MTC/blob/main/ARM_Templete_WindowsServer.json" `
          -adminUsername shiraZadok `
          -adminPassword shsz6457 `
          -dnsLabelPrefix simple-vm2-fkxmkzr5awdd2.eastus.cloudapp.azure.com

      (Get-AzVm -ResourceGroupName ShiraStorageAccount-rg).name