trigger:
- master

pool: Default

steps:
- script: hostname

#- task: GitHubComment@0
#  inputs:
#    gitHubConnection: 'github.com_shiraZadok'
#    repositoryName: 'shiraZadok/AzureRmPipeline_MTC'

#Task 2
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
    
    #New-AzResourceGroupDeployment -Name Deployment-Create_the_first_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json' -TemplateParameterFile 'parameters_sa1.json'
     #New-AzResourceGroupDeployment -Name Deployment-Create_the_second_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json' -TemplateParameterFile 'parameters_sa2.json'
      #For ($i=0; $i -lt 1; $i++) {
     #New-AzResourceGroupDeployment -Name Deployment-Create_the_first_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'Generally_Template_StorageAccount.json'}

#Task 3
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      
      #New-AzResourceGroupDeployment -Name Deployment_create_VM -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'WindowsServerTemplate.json' -TemplateParameterFile 'WindowsServerParameters.json'

#Task 5
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $ResourceGroupName= "ShiraStorageAccount-rg"
      $srcStorageAccountName = "mysorage11"
      $destStorageAccountName = "mysorage22"

      $srcStorageAccountContex = (Get-AzStorageAccount -ResourceGroupName $ResourceGroupName -Name $srcStorageAccountName).Context
      $destStorageAccountContex = (Get-AzStorageAccount -ResourceGroupName $ResourceGroupName -Name $destStorageAccountName).Context
      $srcContainer = "sourcecontainer"
      $destContainer = "destcontainer"

       #Create source and destination container
      #New-AzStorageContainer -Name $srcContainer -Context $srcStorageAccountContex -Permission blob
      #New-AzStorageContainer -Name $destContainer -Context $destStorageAccountContex -Permission blob

      $srcStorageKey = Get-AzStorageAccountKey -Name $srcStorageAccountName `
                                         -ResourceGroupName $ResourceGroupName 
      $destStorageKey = Get-AzStorageAccountKey -Name $destStorageAccountName `
                                          -ResourceGroupName $ResourceGroupName

      $srcContext = New-AzStorageContext -StorageAccountName $srcStorageAccountName `
                                   -StorageAccountKey $srcStorageKey.Value[0]
      $destContext = New-AzStorageContext -StorageAccountName $destStorageAccountName `
                                    -StorageAccountKey $destStorageKey.Value[0]
      #$blobName= "100Blobs"
      Get-ChildItem -Path C:\Users\ShiraZadok\Microsoft\100Blobs | Set-AzStorageBlobContent -Container $srcStorageAccountContex  -Container $srcContainer `
      -Blob $blobName `
      -Context $srcContext


