trigger:
- master

pool: Default

steps:
- script: hostname

#- task: GitHubComment@0
#  inputs:
#    gitHubConnection: 'github.com_shiraZadok'
#    repositoryName: 'shiraZadok/AzureRmPipeline_MTC'

#Task 2
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
    
    #New-AzResourceGroupDeployment -Name Deployment-Create_the_first_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json' -TemplateParameterFile 'parameters_sa1.json'
     #New-AzResourceGroupDeployment -Name Deployment-Create_the_second_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json' -TemplateParameterFile 'parameters_sa2.json'
      #For ($i=0; $i -lt 1; $i++) {
     #New-AzResourceGroupDeployment -Name Deployment-Create_the_first_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'Generally_Template_StorageAccount.json'}

#Task 3
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      
      #New-AzResourceGroupDeployment -Name Deployment_create_VM -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'WindowsServerTemplate.json' -TemplateParameterFile 'WindowsServerParameters.json'

#Task 5
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $ResourceGroupName= "ShiraStorageAccount-rg"
      $srcStorageAccountName = "mysorage11"
      $srcContainer = "sourcecontainer"
      $srcStorageKey = Get-AzStorageAccountKey -Name $srcStorageAccountName `
                                         -ResourceGroupName $ResourceGroupName 

      $srcContext = New-AzStorageContext -StorageAccountName $srcStorageAccountName `
                                   -StorageAccountKey $srcStorageKey.Value[0]

      Get-ChildItem -Path C:\Users\ShiraZadok\Microsoft\100Blobs | Set-AzStorageBlobContent -Container $srcContainer `
      -Context $srcContext -Force

      azcopy copy "https://mysorage11.blob.core.windows.net/sourcecontainer?sv=2020-08-04&ss=bfqt&srt=co&sp=rwdlacuptfx&se=2021-09-10T04:03:56Z&st=2021-08-26T20:03:56Z&spr=https&sig=f4o4yp8lW8nTmwk9rI6hH6aJpp81DkW%2FoyEC1x7i8mU%3D" "https://mysorage22.blob.core.windows.net/destcontainer?sv=2020-08-04&ss=bfqt&srt=co&sp=rwdlacuptfx&se=2021-09-10T04:05:44Z&st=2021-08-26T20:05:44Z&spr=https&sig=lRf8nc%2FJnoX%2BAzGQBzVIXsmcRZggPWO2RCoSzYIVOjE%3D" --recursive


