stages:
  - stage: Build
    jobs:
    - job: Build

  - stage: Deploy
    jobs:
    - job: Deploy
      pool: Default
      steps:
          - script: hostname
          - task: AzureCLI@0
            inputs:
              scriptLocation: 'inlineScript'
              inlineScript: 'az storage container create -n shira-myfirstcontainer'
            
  
