trigger:
- master

pool: Default

steps:

- script: hostname

- task: GitHubComment@0
  inputs:
    gitHubConnection: 'github.com_shiraZadok'
    repositoryName: 'shiraZadok/AzureRmPipeline_MTC'

- task: CmdLine@2
  inputs:
   script: Connect-AzAccount



  
     


#stages:
#  - stage: Deploy
#    jobs:
#    - job: Deploy
      


#          - task: CmdLine@2
#            inputs:
#              script: set AZURE_STORAGE_ACCOUNT
#                      AZURE_STORAGE_KEY
#                      set AZURE_STORAGE_CONNECTION_STRING environment variable
#                      az storage container create -n mystoragecontainer
#                      New-AzStorageContainer -Name "quickstartblobs" -Context $ctx -Permission blob.