trigger:
- master

pool: Default

steps:
- script: hostname

#- task: GitHubComment@0
#  inputs:
#    gitHubConnection: 'github.com_shiraZadok'
#    repositoryName: 'shiraZadok/AzureRmPipeline_MTC'

#Task 2
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
          New-AzResourceGroupDeployment -Name Deployment-Create_the_first_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json' -TemplateParameterFile 'parameters_sa1.json'
          New-AzResourceGroupDeployment -Name Deployment-Create_the_second_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json' -TemplateParameterFile 'parameters_sa2.json'

#Task 3
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $resourceGroupName = Read-Host -Prompt "ShiraStorageAccount-rg"
      $location = Read-Host -Prompt "East US"
      $adminUsername = Read-Host -Prompt "shiraZadok"
      $adminPassword = Read-Host -Prompt "shsz6457" -AsSecureString
      $dnsLabelPrefix = Read-Host -Prompt "simple-vm2-fkxmkzr5awdd2.eastus.cloudapp.azure.com"

      New-AzResourceGroup -Name $resourceGroupName -Location "$location"
      New-AzResourceGroupDeployment `
          -ResourceGroupName $resourceGroupName `
          -TemplateUri "https://github.com/shiraZadok/AzureRmPipeline_MTC/blob/main/ARM_Templete_WindowsServer.json" `
          -adminUsername $adminUsername `
          -adminPassword $adminPassword `
          -dnsLabelPrefix $dnsLabelPrefix

      (Get-AzVm -ResourceGroupName $resourceGroupName).name