stages:
  - stage: Deploy
    jobs:
    - job: Deploy
      pool: Default
      steps:
          - script: hostname
          - task: CmdLine@2
            inputs:
              script: set AZURE_STORAGE_ACCOUNT
                      AZURE_STORAGE_KEY
                      set AZURE_STORAGE_CONNECTION_STRING environment variable
                      az storage container create -n mystoragecontainer
#                      New-AzStorageContainer -Name "quickstartblobs" -Context $ctx -Permission blob.