stages:
  - stage: Deploy
    jobs:
    - job: Deploy
      pool: Default
      steps:
          - script: hostname
          - task: CmdLine@2
            inputs:
              script: |
                      New-AzStorageContainer -Name "quickstartblobs" -Context $ctx -Permission blob.