trigger:
- master

pool: Default

steps:
- script: hostname

#- task: GitHubComment@0
#  inputs:
#    gitHubConnection: 'github.com_shiraZadok'
#    repositoryName: 'shiraZadok/AzureRmPipeline_MTC'

#Task 2
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
    
    #New-AzResourceGroupDeployment -Name Deployment-Create_the_first_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json' -TemplateParameterFile 'parameters_sa1.json'
     #New-AzResourceGroupDeployment -Name Deployment-Create_the_second_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json' -TemplateParameterFile 'parameters_sa2.json'
      #For ($i=0; $i -lt 1; $i++) {
     #New-AzResourceGroupDeployment -Name Deployment-Create_the_first_storageaccount -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'Generally_Template_StorageAccount.json'}

#Task 3
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      
      #New-AzResourceGroupDeployment -Name Deployment_create_VM -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'WindowsServerTemplate.json' -TemplateParameterFile 'WindowsServerParameters.json'

#Task 5
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $srcContext = (Get-AzStorageAccount -ResourceGroupName "ShiraStorageAccount-rg" -Name "mysorage11").Context
      $destContext = (Get-AzStorageAccount -ResourceGroupName "ShiraStorageAccount-rg" -Name "mysorage22").Context
      $srcContainer = "sourcecontainer"
      $destContainer = "destcontainer"

       #Create source and destination container
      #New-AzStorageContainer -Name $srcContainer -Context $srcContext -Permission blob
      #New-AzStorageContainer -Name $destContainer -Context $destContext -Permission blob

       #Uplad blobs to the conatainer
      Set-AzStorageBlobContent -File "C:\Users\ShiraZadok\Microsoft\microsoft-1.png" `
      -Container $srcContainer `
      -Blob "‏‏‏‏‏‏microsoft-1.png" `
      -Context $srcContext -Force
      AzCopy 'https://mysorage11.blob.core.windows.net/sourcecontainer?sv=2020-08-04&ss=bfqt&srt=c&sp=rwdlacuptfx&se=2021-09-25T23:56:47Z&st=2021-08-26T15:56:47Z&spr=https&sig=dO5rexAb%2B94QiODamd5gL8C0O6Lnfn5ye%2FwVYih7JvI%3D' 'https://mysorage22.blob.core.windows.net/destcontainer' --recursive

       #Copy blobs from SrcContainer to DestContainer
       #$copyOperation = Start-AzStorageBlobCopy -SrcBlob "microsoft-1.png" `
       #                                  -SrcContainer $srcContainer `
       #                                  -Context $srcContext `
       #                                  -DestBlob "microsoft-1.png" `
       #                                  -DestContainer $destContainer `
       #                                  -destContext $destContext
