trigger:
- master

pool: Default

steps:
- script: hostname

- task: GitHubComment@0
  inputs:
    gitHubConnection: 'github.com_shiraZadok'
    repositoryName: 'shiraZadok/AzureRmPipeline_MTC'

#Task 2
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      For ($i=0; $i -lt 2; $i++) {
      New-AzResourceGroupDeployment -Name ExampleDeployment -ResourceGroupName ShiraStorageAccount-rg -TemplateFile 'ARM_Templete_StorageAccount.json'
      }

#Task 3
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '(Get-AzVm -ResourceGroupName $resourceGroupName = "ShiraStorageAccount-rg").ARM_Templete_WindowsServer.json'